apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: the-container
        image: 899763172859.dkr.ecr.ap-northeast-1.amazonaws.com/nozaki/node-web-app:v2
        # command: ["/hello",
        #           "--port=8080",
        #           "--enableRiskyFeature=$(ENABLE_RISKY)"]
        ports:
        - containerPort: 8080
        # env:
        # - name: ALT_GREETING
        #   valueFrom:
        #     configMapKeyRef:
        #       name: the-map
        #       key: altGreeting
        # - name: ENABLE_RISKY
        #   valueFrom:
        #     configMapKeyRef:
        #       name: the-map
        #       key: enableRisky
