apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: the-container
        image: 899763172859.dkr.ecr.ap-northeast-1.amazonaws.com/nozaki/node-web-app:v5
        # command: ["/hello",
        #           "--port=8080",
        #           "--enableRiskyFeature=$(ENABLE_RISKY)"]
        envFrom:  # env ではなく envFrom
        - secretRef:
            name: mysecret # ConfigMap の name を指定。すべてのキーが環境変数として展開される
          # prefix: MY_PREFIX_     # 名前衝突しないように prefix を指定することもできる
        # Secret の場合は secretRef で Secret の name を指定
        ports:
        - containerPort: 8080
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
        # env:
        # - name: ALT_GREETING
        #   valueFrom:
        #     configMapKeyRef:
        #       name: the-map
        #       key: altGreeting
        # - name: ENABLE_RISKY
        #   valueFrom:
        #     configMapKeyRef:
        #       name: the-map
        #       key: enableRisky
